baseURL = "https://MaxJulianos.github.io/github-pages-cicd-MaxJulianos/"
title = "StatGen"
languageCode = "pt-br"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  description = "StatGen — gerador e visualizador de estatísticas"
  author = "Juliano"
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Início"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Sobre"
    url = "/sobre/"
    weight = 2
